{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.0.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.1.3.jar",
          "url": "spring-boot-3.1.3.jar",
          "size": 1534847,
          "sha512": "955c4508964a6b31ec559009e7caef4c213ed2246f89e01e1dee17c897e7a89e040909bd3874921a54f59b5a8dc415560b74465698ae2141ed159395c8e2ebfe",
          "sha256": "68a70b82733bb4b3993e9b8d4dcdb5507db8be4aeaa653aa816ad3e3300e9ab8",
          "sha1": "7161dbfbbdde423513c89deae00da8068319a26a",
          "md5": "5e866998222dd307f7f884bbe151a499"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.0.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.1.3.jar",
          "url": "spring-boot-3.1.3.jar",
          "size": 1534847,
          "sha512": "955c4508964a6b31ec559009e7caef4c213ed2246f89e01e1dee17c897e7a89e040909bd3874921a54f59b5a8dc415560b74465698ae2141ed159395c8e2ebfe",
          "sha256": "68a70b82733bb4b3993e9b8d4dcdb5507db8be4aeaa653aa816ad3e3300e9ab8",
          "sha1": "7161dbfbbdde423513c89deae00da8068319a26a",
          "md5": "5e866998222dd307f7f884bbe151a499"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.1.3-javadoc.jar",
          "url": "spring-boot-3.1.3-javadoc.jar",
          "size": 2245264,
          "sha512": "e9ec1eaefca2bd3f4ba90da8040f9af5779015c64d556698275ac876f390e7735e0cbed40d0935e6f724688d50a8bdcb1a1b4094b47bdbdfbf2ca01f594762fd",
          "sha256": "b977c1f516a754d0a0607bdb63da70cae0f192b2332e43cdfc3c549e7546d122",
          "sha1": "7552146b714301787822be167f28014050ffbf8e",
          "md5": "0d12e0756fc4b9f5725f36c4fd3cf840"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.1.3-sources.jar",
          "url": "spring-boot-3.1.3-sources.jar",
          "size": 1065958,
          "sha512": "5dd2afae0c1a5ce2aeae32b06e91c6be1fb2177bcfa330f5177a053a1147e74d01289e16492a9ccacae9b0ec2342dbcacad92192d90cdbbbf82465e4553f09b7",
          "sha256": "947903b06ed03cd061b56fca60925ef20b0b7f39ffa65ebd5d0f3e53764fddc6",
          "sha1": "cf3c93dac83985ef8abe4113b429e465130dd48c",
          "md5": "1a3fd3899c241523b0c07a76b9fd0fe2"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-3.1.3.jar",
          "url": "spring-boot-3.1.3.jar",
          "size": 1534847,
          "sha512": "955c4508964a6b31ec559009e7caef4c213ed2246f89e01e1dee17c897e7a89e040909bd3874921a54f59b5a8dc415560b74465698ae2141ed159395c8e2ebfe",
          "sha256": "68a70b82733bb4b3993e9b8d4dcdb5507db8be4aeaa653aa816ad3e3300e9ab8",
          "sha1": "7161dbfbbdde423513c89deae00da8068319a26a",
          "md5": "5e866998222dd307f7f884bbe151a499"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-maven-optional",
          "version": "3.1.3"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.1.3.jar",
          "url": "spring-boot-3.1.3.jar",
          "size": 1534847,
          "sha512": "955c4508964a6b31ec559009e7caef4c213ed2246f89e01e1dee17c897e7a89e040909bd3874921a54f59b5a8dc415560b74465698ae2141ed159395c8e2ebfe",
          "sha256": "68a70b82733bb4b3993e9b8d4dcdb5507db8be4aeaa653aa816ad3e3300e9ab8",
          "sha1": "7161dbfbbdde423513c89deae00da8068319a26a",
          "md5": "5e866998222dd307f7f884bbe151a499"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-maven-optional",
          "version": "3.1.3"
        }
      ]
    }
  ]
}
