{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.1.3.jar",
          "url": "spring-boot-test-3.1.3.jar",
          "size": 247972,
          "sha512": "daffee761d33b0eb142abb3dd67e25c17aed2e4969cb58e834d9ba2732f873e0a5e79a6011191853045ee2d330ae995e35c3261cb6cc9526a8a289b26fbb1909",
          "sha256": "f648f4330671c71d210f682c381d6b7ae0dee5063e407ed39c957a64a8f8bafa",
          "sha1": "ca42cbb95b14f5579a4023e0d5df2645fb3f535a",
          "md5": "a23419bee4d8e0c3db5f794e5ec10cf4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.1.3.jar",
          "url": "spring-boot-test-3.1.3.jar",
          "size": 247972,
          "sha512": "daffee761d33b0eb142abb3dd67e25c17aed2e4969cb58e834d9ba2732f873e0a5e79a6011191853045ee2d330ae995e35c3261cb6cc9526a8a289b26fbb1909",
          "sha256": "f648f4330671c71d210f682c381d6b7ae0dee5063e407ed39c957a64a8f8bafa",
          "sha1": "ca42cbb95b14f5579a4023e0d5df2645fb3f535a",
          "md5": "a23419bee4d8e0c3db5f794e5ec10cf4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.1.3-javadoc.jar",
          "url": "spring-boot-test-3.1.3-javadoc.jar",
          "size": 413136,
          "sha512": "efc8edc2f129e56ee4739c3b1d81e8855b285e7d37b11a25548b86eb9f4ba38d139241f1b1b7cc4e02bce1d7633f11c872e6f0598606b4400cd5a9ca85bb4619",
          "sha256": "71f3d31b24956f9ea89bbb8dd16da7edbaf22ceeb5f094c6b1c325c3df1ebc2a",
          "sha1": "0e2e7ed058c2a502508d4e16203273e249793efe",
          "md5": "1f4ba97ff89314b8dfb5c328d6259675"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.1.3-sources.jar",
          "url": "spring-boot-test-3.1.3-sources.jar",
          "size": 167894,
          "sha512": "0ca3d20235f41b0aa8ed459549e6f75eaa2674b47ea6c1652f720fe46f2d50cda7389cf8da4c920a51f8f58e9606b9644f84cc6a731adb8ffc8ea4a02926f013",
          "sha256": "e5fd28386424b057342bbe0cf708b6fbff5120ec3155aef6560c9ca7e2d567c5",
          "sha1": "8e52e04bec86a6ba912407df225ec160db12954e",
          "md5": "c0b155476a8de8e95fc43f565997a7fa"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-test-3.1.3.jar",
          "url": "spring-boot-test-3.1.3.jar",
          "size": 247972,
          "sha512": "daffee761d33b0eb142abb3dd67e25c17aed2e4969cb58e834d9ba2732f873e0a5e79a6011191853045ee2d330ae995e35c3261cb6cc9526a8a289b26fbb1909",
          "sha256": "f648f4330671c71d210f682c381d6b7ae0dee5063e407ed39c957a64a8f8bafa",
          "sha1": "ca42cbb95b14f5579a4023e0d5df2645fb3f535a",
          "md5": "a23419bee4d8e0c3db5f794e5ec10cf4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-maven-optional",
          "version": "3.1.3"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.1.3.jar",
          "url": "spring-boot-test-3.1.3.jar",
          "size": 247972,
          "sha512": "daffee761d33b0eb142abb3dd67e25c17aed2e4969cb58e834d9ba2732f873e0a5e79a6011191853045ee2d330ae995e35c3261cb6cc9526a8a289b26fbb1909",
          "sha256": "f648f4330671c71d210f682c381d6b7ae0dee5063e407ed39c957a64a8f8bafa",
          "sha1": "ca42cbb95b14f5579a4023e0d5df2645fb3f535a",
          "md5": "a23419bee4d8e0c3db5f794e5ec10cf4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-maven-optional",
          "version": "3.1.3"
        }
      ]
    }
  ]
}
