{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-loader-tools",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-3.1.3.jar",
          "url": "spring-boot-loader-tools-3.1.3.jar",
          "size": 250660,
          "sha512": "93dbb1d112b7a4ae606d4eaab03e2602044e5616558ba237d5e260b34344318a9bd55ca45cbe9bbb25e3cf6b4de6a8f9d27a1e6aeadc5418558b329b9eb37cfc",
          "sha256": "60ae94149bade0d9098a7be311027b11762a1afce4067c45927c7658c2c8c47b",
          "sha1": "03a0ac363891697d74668d01b86460869b732bb7",
          "md5": "279fff29a8226c4cfd78b1c61226883b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-3.1.3.jar",
          "url": "spring-boot-loader-tools-3.1.3.jar",
          "size": 250660,
          "sha512": "93dbb1d112b7a4ae606d4eaab03e2602044e5616558ba237d5e260b34344318a9bd55ca45cbe9bbb25e3cf6b4de6a8f9d27a1e6aeadc5418558b329b9eb37cfc",
          "sha256": "60ae94149bade0d9098a7be311027b11762a1afce4067c45927c7658c2c8c47b",
          "sha1": "03a0ac363891697d74668d01b86460869b732bb7",
          "md5": "279fff29a8226c4cfd78b1c61226883b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.1.3-javadoc.jar",
          "url": "spring-boot-loader-tools-3.1.3-javadoc.jar",
          "size": 245832,
          "sha512": "6e41ac314d4cdc919bd3dca402bc6d2b2add2c1c06ea660c5061e81a8ad18044844f8f5d4cc6e286c2cc3cec24ef53af9f5f7df6539e0ca43326ef510ad0cf01",
          "sha256": "c46e56361edb2feca57f6df59d94d612f71e92597aa35df5460e85a257fe84b6",
          "sha1": "bbd1f7bc1b8a182a2476210579b7fb48376c1a57",
          "md5": "c660a057e0ea14399b700bfc8c67f508"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.1.3-sources.jar",
          "url": "spring-boot-loader-tools-3.1.3-sources.jar",
          "size": 73273,
          "sha512": "6f173060f96b18aa35d5ae64f94bcb0b1235af05e192c869612d21a90fb6456e4333030de824cd09a7f3e346216f93983d69f656043ad26af4f58de19e99bd5a",
          "sha256": "5c6cbd223ae747d61d5e50e658d332e8a9b20b0a9ad7dd99edbda93f74499aa2",
          "sha1": "b838dc385524c15548ea762224ff052c26d0886c",
          "md5": "6bb4dc69ee995e2d49148c53f536af87"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.1.3.jar",
          "url": "spring-boot-loader-tools-3.1.3.jar",
          "size": 250660,
          "sha512": "93dbb1d112b7a4ae606d4eaab03e2602044e5616558ba237d5e260b34344318a9bd55ca45cbe9bbb25e3cf6b4de6a8f9d27a1e6aeadc5418558b329b9eb37cfc",
          "sha256": "60ae94149bade0d9098a7be311027b11762a1afce4067c45927c7658c2c8c47b",
          "sha1": "03a0ac363891697d74668d01b86460869b732bb7",
          "md5": "279fff29a8226c4cfd78b1c61226883b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-loader-tools-maven-optional",
          "version": "3.1.3"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.1.3.jar",
          "url": "spring-boot-loader-tools-3.1.3.jar",
          "size": 250660,
          "sha512": "93dbb1d112b7a4ae606d4eaab03e2602044e5616558ba237d5e260b34344318a9bd55ca45cbe9bbb25e3cf6b4de6a8f9d27a1e6aeadc5418558b329b9eb37cfc",
          "sha256": "60ae94149bade0d9098a7be311027b11762a1afce4067c45927c7658c2c8c47b",
          "sha1": "03a0ac363891697d74668d01b86460869b732bb7",
          "md5": "279fff29a8226c4cfd78b1c61226883b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-loader-tools-maven-optional",
          "version": "3.1.3"
        }
      ]
    }
  ]
}
